name: Test and Deploy

on:
  push:
    branches:
      - main
jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy:
    needs: run-test
    runs-on: ubuntu-20.04
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SECRET_IP}}
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD}}
          port: ${{ secrets.SECRET_PORT }}
          
          script: |
            cd /home/test-app
            echo 'Entering /home/test-app directory'
            git pull
            echo 'Repository has been pulled'
            systemctl restart test-app.service
            systemctl status test-app.service
